### ISSUE TITLE
Avatars mentors

### ISSUE THREAD

**Issue by cappert** [lyonrb/railsgirly#7]

**Comment by gbarillot** [comment]
Je suis (enfin) dispo, mais juste Samedi, pas le vendredi soir.

**Comment by cappert** [comment]
joli gravatar @gbarillot :)

**Comment by cappert** [comment]
Maxime Jonckiere dit : "plus user-friendly y'a la photo de [mon compte meetup](http://www.meetup.com/members/80603862/)"
![highres_97776262](https://cloud.githubusercontent.com/assets/71031/5071691/5f861aba-6e73-11e4-9e2d-10920ed22d1f.jpg)

**Comment by cappert** [comment]
@franckverrot -> gravatar

**Comment by m4tm4t** [comment]
Mon gravatar: ...
edit: ok

**Comment by mehlah** [comment]
gravatar: . == GitHub
